# **Sommaire** #

[Partie 1](#partie-1)
    [Question 1](#p1-question-1-)  
    [Question 2](#p1-question-2-)
    [Question 3](#p1-question-3-)
[Partie 2](#partie-2)


## **Partie 1** ##
------
### **P1-Question 1 :** ###
------
Un couple valeur propre/vecteur propre est défini de cette manière : $AX = λX$.
Où $A$ est la matrice étudiée, $X$ est le vecteur propre et $λ$ la valeur propre associée à ce vecteur. 
En appliquant cette définition à la matrice $Q$, on obtient $QX = λX$. 

Dans l'énoncé, on définit le vecteur de score par l'équation suivante $r = Qr$. 
En remplaçant $X$ par $r$ dans la définition on obtient $Qr = λr$, ainsi le but est de trouver le vecteur propre $r$ pour une valeur propre λ de 1. 

L'algorithme de la puissance itérée permet donc de calculer une approximation d'une valeur propre ainsi que son vecteur propre associé. 
De plus, lorsque l'algorithme de la puissance itérée est appliqué à une matrice stochastique, il renvoie automatiquement une valeur approchée du vecteur propre de la matrice quand $λ = 1$. 
Ainsi, il faut démontrer que $Q$ est une matrice stochastique.

Une matrice est stochastique si toutes les sommes des valeurs de chaque colonne est égale à 1 et que toutes ses valeurs sont comprises entre 0 et 1.

Démontrons d'abord que les sommes des valeurs de chacunes de ses colonnes sont égales à 1.

$$

Q_j = \displaystyle\sum_{j=1}^N \frac{c_{i,j}}{N_j}  

\equiv Q_j = \displaystyle\frac{1}{N_j}\sum_{j=1}^N c_{i,j}  

$$
De plus, 
$$
N_j = \displaystyle\sum_{j=1}^N c_{i,j}
$$

Ainsi on a :

$$

Q_j = \displaystyle\frac{\displaystyle\sum_{j=1}^N c_{i,j}}{\displaystyle\sum_{j=1}^N c_{i,j}}

\equiv Q_j = 1 

$$

D'où chaque colonne de Q, est égale à 1.

Finalement, nous allons démontrer que toute valeur de Q est comprise entre 0 et 1.

On a donc :

$$q_{i,j} = \displaystyle\frac{c_{i,j}}{N_j}$$ avec $$c_{i,j}\in\ {0,1} $$ et $$ N_j\in\ N$$

Or la division de 1 ou 0 par un nombre entier est forcément comprise entre 0 et 1.

Donc Q remplie les 2 conditions pour être une matrice stochastique.

C'est pourquoi en appliquant l'algorithme de la puissance itérée sur la matrice $Q$, on obtient le vecteur $r$ contenant tous les scores des pages.

-----





### **P1-Question 2 :** ###


In [21]:
import numpy as np
import random

def norme(vecteur):
    return np.sqrt(np.sum(vecteur**2))


def creer_matriceQ(matriceAdjacence):
    
    matriceC = matriceAdjacence.transpose()

    matriceQ = [[0 for i in range(len(matriceAdjacence))] for i in range(len(matriceAdjacence))]

    N_J = [0 for i in range(len(matriceAdjacence))]


    for indiceColonne in range(len(matriceAdjacence)):

        for indiceLigne in range(len(matriceAdjacence)):

            N_J[indiceColonne] += matriceC[indiceLigne][indiceColonne]


    for indiceLigne in range(len(matriceAdjacence)):

        for indiceColonne in range(len(matriceAdjacence)):

            if N_J[indiceColonne] != 0 :

                matriceQ[indiceLigne][indiceColonne] = matriceC[indiceLigne][indiceColonne]/N_J[indiceColonne]

    return np.array(matriceQ)


def puissance_iteree(matriceAdjacence, Precision, vecteurDepart):

    matriceQ = creer_matriceQ(matriceAdjacence)
    vecteurCourant = vecteurDepart
    vecteurSuivant = matriceQ @ vecteurCourant

    while (norme(vecteurSuivant - vecteurCourant) > Precision ):

        vecteurCourant = vecteurSuivant
        vecteurSuivant = matriceQ @ vecteurCourant

    return vecteurCourant / norme(vecteurCourant), norme(vecteurCourant/norme(vecteurCourant))

matriceGrapheN14 = np.array([[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], 
                             [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                             [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                             [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                             [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                             [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0], 
                             [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], 
                             [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], 
                             [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0], 
                             [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1], 
                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1], 
                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0], 
                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0], 
                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]])

precision1 = 0.01
precision2 = 0.001
precision3 = 0.000001

vecteurDepart = np.array([[random.random()] for i in range(len(matriceGrapheN14))])


print(f"\n|----- VECTEURS PROPRES -----|\n")

print(f"Vecteur propre :\n",puissance_iteree(matriceGrapheN14, precision1, vecteurDepart)[0],
        "\n avec une précision de ", precision1)

print(f"Vecteur propre :\n",puissance_iteree(matriceGrapheN14, precision2, vecteurDepart)[0],
        "\n avec une précision de ", precision2)

print(f"Vecteur propre :\n",puissance_iteree(matriceGrapheN14, precision3, vecteurDepart)[0],
        "\n avec une précision de ", precision3)


#Verifictions numériques r = Qr <-> Qr - r = 0

matriceQ = creer_matriceQ(matriceGrapheN14)

QrMinus_r_Precision1 = norme((matriceQ @ puissance_iteree(matriceGrapheN14, precision1, vecteurDepart)[0])
- puissance_iteree(matriceGrapheN14, precision1, vecteurDepart)[0])

QrMinus_r_Precision2 = norme((matriceQ @ puissance_iteree(matriceGrapheN14, precision2, vecteurDepart)[0])
- puissance_iteree(matriceGrapheN14, precision2, vecteurDepart)[0])

QrMinus_r_Precision3 = norme((matriceQ @ puissance_iteree(matriceGrapheN14, precision3, vecteurDepart)[0]) 
- puissance_iteree(matriceGrapheN14, precision3, vecteurDepart)[0])

print(f"\n|----- VERIFICATIONS NUMERIQUES -----|\n")

print(f"Vérification de Qr - r = 0  avec une précision de {precision1} :  {QrMinus_r_Precision1:.15f} \n")

print(f"Vérification de Qr - r = 0 avec une précision de  {precision2} : {QrMinus_r_Precision2:.15f} \n")

print(f"Vérification de Qr - r = 0 avec une précision de {precision3} : {QrMinus_r_Precision3:.15f} \n")








|----- VECTEURS PROPRES -----|

Vecteur propre :
 [[0.4506639 ]
 [0.18276029]
 [0.18276953]
 [0.18276894]
 [0.18275511]
 [0.49829806]
 [0.16444158]
 [0.32974279]
 [0.16444158]
 [0.39332835]
 [0.15610149]
 [0.15610181]
 [0.15610753]
 [0.15609801]] 
 avec une précision de  0.01
Vecteur propre :
 [[0.42335087]
 [0.16958636]
 [0.16958636]
 [0.16958636]
 [0.16958636]
 [0.50348677]
 [0.16782805]
 [0.33565496]
 [0.16782805]
 [0.41581867]
 [0.16608361]
 [0.16608361]
 [0.16608361]
 [0.16608361]] 
 avec une précision de  0.001
Vecteur propre :
 [[0.41959453]
 [0.16783806]
 [0.16783806]
 [0.16783806]
 [0.16783806]
 [0.50350881]
 [0.16783627]
 [0.33567254]
 [0.16783627]
 [0.41958683]
 [0.16783448]
 [0.16783448]
 [0.16783448]
 [0.16783448]] 
 avec une précision de  1e-06

|----- VERIFICATIONS NUMERIQUES -----|

Vérification de Qr - r = 0  avec une précision de 0.01 :  0.004863159981432 

Vérification de Qr - r = 0 avec une précision de  0.001 : 0.000508631571039 

Vérification de Qr - r = 0 avec u

De plus on sait que le vecteur $r$ noté vecteurCourant dans notre programme, au bout d'un nombre important d'itérations car d'après le cours pour presque tout $$X_{0}\in R^n, (X_{n})_{n}$$ converge vers un vecteur propre pour la valeur propre 1.
C'est à dire que pour un nombre important d'itérations, vecteurCourant se rapproche de $r$.  
On a donc :  
$$Qr = r \displaystyle\equiv\ Qr - r = 0.$$
Donc pour vérifier numériquement que vecteurCourant $\approx r$, on peut tout simplement remplacer dans l'équation donnée ci-dessus $Q$ par matriceQ et $r$ par vecteurCourant et calculer le résultat. C'est ce qu'on a stocké dans les variables QrMinus_r_Precision $N$, une pour chaque précision. Finalement, plus ces résultats se rapproche de 0, plus l'approximation est précise d'après la relation énoncée précedemment.

----

### **P1-Question 3** : ### 
On remarque que notre algorithme est cohérent avec le graphe présenté en partie 1.
En effet, les sommets 1 et 10 ont tous les deux le même degré entrant (5). Les sommets référençant les sommets mentionnés ont tous un degré sortant de 1, ce qui résulte pour les sommets 1 et 10 d'obtenir la moitié des scores pour chaque sommet.
En raison de la symétrie du graphe, on constate une symétrie des résultats des scores, en particulier pour les sommets 1 et 10, le sommet 1 ayant un score approximatif de 0.55926881 et le sommet 10 un score approximatif de 0.5555402, en raison des causes mentionnées ci-dessus.
Le sommet 8 a comme sommets entrants 6, 7 et 9. Cependant, ces sommets possèdent des degrés sortants bien plus élevés que précédemment (3 pour 6 ; 2 pour 7 ; 2 pour 9), ce qui divise le score qu'ils délèguent au sommet 8 par la valeur de leur degré sortant. Par conséquent, le score du sommet 8 est dépendant de ces facteurs.
<br>

Les sommets 1 et 10 ont un référencement similaire, ce qui a pour conséquence qu'ils ont également un score similaire. On peut le constater lorsqu'on regarde le renvoi de la fonction de la puissance itérée, avec un score d'approximativement 0.55926881 pour 1 et un score approximatif de 0.5555402 pour 10.

-----

## **Partie 2** ##

----

### **P2-Question 1 :** ###



In [4]:

matriceGrapheN5 = np.array([[0, 0, 0, 0, 0],
                            [1, 0, 0, 0, 0],
                            [1, 0, 0, 1, 0],
                            [1, 1, 0, 0, 0], 
                            [1, 1, 0, 0, 0]])

vecteurDepartN5 = np.array([[random.random()] for i in range(len(matriceGrapheN5))])

print(f"\n|----- VECTEURS PROPRES -----|\n")

print(f"Vecteur propre :\n",puissance_iteree(matriceGrapheN5, precision1, vecteurDepartN5)[0],
        "\n avec une précision de ", precision1)

print(f"Vecteur propre :\n",puissance_iteree(matriceGrapheN5, precision2, vecteurDepartN5)[0],
        "\n avec une précision de ", precision2)

print(f"Vecteur propre :\n",puissance_iteree(matriceGrapheN5, precision3, vecteurDepartN5)[0],
        "\n avec une précision de ", precision3)




|----- VECTEURS PROPRES -----|

Vecteur propre :
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]] 
 avec une précision de  0.01
Vecteur propre :
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]] 
 avec une précision de  0.001
Vecteur propre :
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]] 
 avec une précision de  0.0001


C:\Users\lenaf\AppData\Local\Temp\ipykernel_31788\2159655344.py:45: RuntimeWarning: invalid value encountered in divide
  return vecteurCourant / norme(vecteurCourant), norme(vecteurCourant/norme(vecteurCourant))


On peut observer que le vecteur propre donné par l'implémentation de l'algorithme faite précédemment renvoit une erreur de valeur interdite dans la division entre le vecteurCourant et sa norme. La seule valeur interdite de la division étant 0, on peut donc conclure que appliquée à ce graphe, notre implémentation renvoit un vecteur nul. Or un vecteur propre est par définition non nul, on peut donc conclure que notre implémentation ne renvoit pas le vecteur propre de $Q$ quand $$\lambda = 1 .$$ Ainsi notre implémentation n'est pas valide sur ce graphe. On peut conjecturer que c'est parce que le graphe posséde une ligne et un colonne composée entièrement de 0.

----

### **P2-Question 2 :** ###

In [22]:
def creer_matriceP(matriceQ, alpha):

    N = len(matriceQ)
    matriceP = [[0 for i in range(len(matriceQ))] for i in range(len(matriceQ))]
    N_J = [0 for i in range(len(matriceQ))]

    for indiceColonne in range(N):

        for indiceLigne in range(N):

            N_J[indiceColonne] += matriceQ[indiceColonne][indiceLigne]

    for indiceLigne in range(N):

        for indiceColonne in range(N):

            if N_J[indiceColonne] != 0:

                matriceP[indiceLigne][indiceColonne] = (alpha * (matriceQ[indiceLigne][indiceColonne])) + ((1 - alpha)/N)

            else:
                 
                matriceP[indiceLigne][indiceColonne] = 1/N

    return np.array(matriceP)

def PageRankIterative(matriceAdjacence, Precision, vecteurDepart):

    alpha = 0.85
    matriceQ = creer_matriceQ(matriceAdjacence)
    matriceP = creer_matriceP(matriceQ, alpha)
    vecteurCourant = vecteurDepart
    vecteurSuivant = matriceP @ vecteurCourant
 

    while (norme(vecteurSuivant - vecteurCourant) > Precision ):

        vecteurCourant = vecteurSuivant
        vecteurSuivant = matriceP @ vecteurCourant

    return vecteurCourant / norme(vecteurCourant), norme(vecteurCourant/norme(vecteurCourant))

print(f"\n|----- VECTEURS PROPRES -----|\n")

print(f"Vecteur propre :\n",PageRankIterative(matriceGrapheN5, precision1, vecteurDepartN5)[0],
        "\n avec une précision de ", precision1)

print(f"Vecteur propre :\n",PageRankIterative(matriceGrapheN5, precision2, vecteurDepartN5)[0],
        "\n avec une précision de ", precision2)

print(f"Vecteur propre :\n",PageRankIterative(matriceGrapheN5, precision3, vecteurDepartN5)[0],
       "\n avec une précision de ", precision3)

#Verifictions numériques r = Pr <-> Pr - r = 0

matriceQN5 = creer_matriceQ(matriceGrapheN5)

matricePN5 = creer_matriceP(matriceQN5, 0.85)

PrMinus_r_Precision1 = norme((matricePN5 @ PageRankIterative(matriceGrapheN5, precision1, vecteurDepartN5)[0])
- PageRankIterative(matriceGrapheN5, precision1, vecteurDepartN5)[0])

PrMinus_r_Precision2 = norme((matricePN5 @ PageRankIterative(matriceGrapheN5, precision2, vecteurDepartN5)[0])
- PageRankIterative(matriceGrapheN5, precision2, vecteurDepartN5)[0])

PrMinus_r_Precision3 = norme((matricePN5 @ PageRankIterative(matriceGrapheN5, precision3, vecteurDepartN5)[0]) 
- PageRankIterative(matricePN5, precision3, vecteurDepartN5)[0])

print(f"\n|----- VERIFICATIONS NUMERIQUES -----|\n")

print(f"Vérification de Pr - r = 0  avec une précision de {precision1} :  {PrMinus_r_Precision1:.15f} \n")

print(f"Vérification de Pr - r = 0 avec une précision de  {precision2} : {PrMinus_r_Precision2:.15f} \n")

print(f"Vérification de Pr - r = 0 avec une précision de {precision3} : {PrMinus_r_Precision3:.15f} \n")





|----- VECTEURS PROPRES -----|

Vecteur propre :
 [[0.86033291]
 [0.35742797]
 [0.20981939]
 [0.20981939]
 [0.20981939]] 
 avec une précision de  0.01
Vecteur propre :
 [[0.86033351]
 [0.35742769]
 [0.20981873]
 [0.20981873]
 [0.20981873]] 
 avec une précision de  0.001
Vecteur propre :
 [[0.86033351]
 [0.35742769]
 [0.20981873]
 [0.20981873]
 [0.20981873]] 
 avec une précision de  1e-06

|----- VERIFICATIONS NUMERIQUES -----|

Vérification de Pr - r = 0  avec une précision de 0.01 :  0.395882769668967 

Vérification de Pr - r = 0 avec une précision de  0.001 : 0.395883821955479 

Vérification de Pr - r = 0 avec une précision de 1e-06 : 0.849182768876051 



On peut observer que le vecteur propre obtenu, quelque soit la précision, reflète bien les scores de chaque sommet du graphe. En effet, le sommet 1, qui est pointé par tout le monde, a par conséquent le score le plus élevé. En regardant la première ligne du vecteur obtenu qui donne le score du sommet 1 est  la valeur la plus élevée. De plus, les sommets 3, 4 et 5 sont sensés avoir des scores 